# Generated by Django 6.1 on 2026-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_themesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True, verbose_name='插件标识')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='已启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '插件设置',
                'verbose_name_plural': '插件设置',
            },
        ),
    ]
