# Generated by Django 6.1 on 2026-08-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pluginsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
            ],
            options={
                'verbose_name': '导航链接',
                'verbose_name_plural': '导航链接',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
