# Generated by Django 6.1 on 2026-08-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_alter_page_slug_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownSourceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='显示原文按钮')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Markdown 原文视图',
                'verbose_name_plural': 'Markdown 原文视图',
            },
        ),
    ]
