# Generated by Django 6.1 on 2026-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_markdownsourcesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='目标')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
            ],
            options={
                'verbose_name': '分享目标',
                'verbose_name_plural': '分享目标',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
