# Generated by Django 6.1 on 2026-08-30 08:21

from django.db import migrations, models


def convert_is_visible(apps, schema_editor):
    NavItem = apps.get_model("blog", "navitem")
    NavItem.objects.filter(is_visible=False).update(visibility="hidden")


def restore_is_visible(apps, schema_editor):
    NavItem = apps.get_model("blog", "navitem")
    NavItem.objects.filter(visibility="hidden").update(is_visible=False)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_seed_share_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='visibility',
            field=models.CharField(choices=[('all', '所有页面'), ('home', '仅主页'), ('non_home', '仅其它页面'), ('hidden', '隐藏')], default='all', max_length=10, verbose_name='显示范围'),
        ),
        migrations.RunPython(convert_is_visible, restore_is_visible),
        migrations.RemoveField(
            model_name='navitem',
            name='is_visible',
        ),
    ]
