# Generated by Django 6.1 on 2026-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_navitem_is_visible_navitem_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='显示在主页顶部，最长 200 字；留空时使用站点描述。', max_length=200, verbose_name='简介内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主页简介',
                'verbose_name_plural': '主页简介',
            },
        ),
    ]
