# Generated by Django 6.1 on 2026-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_siteabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='show_in_post_header',
            field=models.BooleanField(default=True, verbose_name='显示在文章页顶部导航'),
        ),
    ]
