# Generated by Django 6.1 on 2026-08-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_add_archive_nav_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='浏览器标签页与 RSS 标题；留空时使用站点名称（SITE_NAME）。', max_length=100, verbose_name='网页标题')),
                ('description', models.TextField(blank=True, help_text='meta description；留空时使用 SITE_DESCRIPTION。', max_length=300, verbose_name='站点描述（meta）')),
                ('favicon', models.ImageField(blank=True, help_text='建议 32×32 或 48×48 的 PNG/ICO；留空时不输出 favicon 链接。', null=True, upload_to='site/', verbose_name='Favicon')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点元信息',
                'verbose_name_plural': '站点元信息',
            },
        ),
    ]
