# Generated by Django 6.1 on 2026-08-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_sitemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='name',
            field=models.CharField(blank=True, help_text='页面顶部大标题、页脚版权与 RSS 链接名称；留空时使用站点名称（SITE_NAME）。', max_length=100, verbose_name='站点名称（显示）'),
        ),
    ]
