# Generated by Django 6.1 on 2026-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_merge_siteabout_into_sitemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemeta',
            options={'verbose_name': '站点设置', 'verbose_name_plural': '站点设置'},
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='about',
            field=models.CharField(blank=True, help_text='显示在主页顶部，最长 200 字；留空时使用站点描述。', max_length=200, verbose_name='主页简介'),
        ),
    ]
