# Generated by Django 6.1 on 2026-08-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_sitemeta_options_alter_sitemeta_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='favicon',
            field=models.ImageField(blank=True, help_text='建议 32×32 或 48×48 的 PNG/ICO；留空时使用主题默认的仙人掌 logo。', null=True, upload_to='site/', verbose_name='Favicon'),
        ),
    ]
