# Generated by Django 6.1 on 2026-08-31 00:58

from django.db import migrations, models


def copy_markdown_source_setting(apps, schema_editor):
    """旧单例的开关状态迁入 SiteMeta.show_markdown_source。"""
    OldSetting = apps.get_model("blog", "MarkdownSourceSetting")
    SiteMeta = apps.get_model("blog", "SiteMeta")
    setting = OldSetting.objects.first()
    enabled = setting.is_enabled if setting else True
    for meta in SiteMeta.objects.all():
        meta.show_markdown_source = enabled
        meta.save(update_fields=["show_markdown_source", "updated_at"])

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_sitemeta_favicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkdownSourceSetting',
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='show_markdown_source',
            field=models.BooleanField(default=True, help_text='文章页是否提供“查看 Markdown 原文”入口。', verbose_name='显示原文按钮'),
        ),
    ]
