# Generated by Django 6.1 on 2026-08-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
