# Generated by Django 6.1 on 2026-08-30 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_siteabout'),
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-created_at'], 'verbose_name': '上传图片', 'verbose_name_plural': '上传图片'},
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='blog.post', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/%Y/%m/', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='宽度'),
        ),
    ]
